# Generated by Django 6.0 on 2025-12-29 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='eligible_depts',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='posted_date',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='is_profile_complete',
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(default='Applied', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='skills',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
