# Generated by Django 6.0 on 2025-12-29 15:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_application_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='jobposting',
            name='eligible_depts',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='job_type',
            field=models.CharField(default='Job', max_length=50),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
