# Generated by Django 6.0 on 2025-12-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_announcement_jobposting_eligible_depts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='official_link',
            field=models.URLField(blank=True, help_text="Link to company's career page", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='package_range',
            field=models.CharField(blank=True, help_text='e.g. 5 LPA - 8 LPA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='eligible_depts',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='job_type',
            field=models.CharField(choices=[('Job', 'Placement'), ('Internship', 'Internship'), ('Drive', 'Placement Drive')], max_length=20),
        ),
    ]
