# Generated by Django 6.0 on 2025-12-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_jobposting_official_link_jobposting_package_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='eligible_depts',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
