# Generated by Django 5.1.7 on 2026-01-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_remove_jobposting_eligible_depts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='ats_score',
        ),
        migrations.AddField(
            model_name='application',
            name='eligibility_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
